### ISSUE TITLE
Design Homepage

### ISSUE THREAD

**Issue by kbakeann** [CovidSC/covidsc-web#11]
We need an initial design of the homepage. This should include buttons for "Check symptoms" and "Find resources" as well as the information/graphics below. 

The infographics below the buttons will be subject to change, these will be enhanced once initial mockups roll out.

**Comment by kbakeann** [comment]
https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bb78c56a1630d2f56c/
![Homepage](https://user-images.githubusercontent.com/33105088/77943394-24b3b880-728b-11ea-81c4-1a252790693d.png)

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bf120af47227babcc9/
![Homepage](https://user-images.githubusercontent.com/33105088/77943334-0e0d6180-728b-11ea-8a76-b12b38351027.png)

https://app.zeplin.io/project/5e7e4dc925feed6b33480e5d/screen/5e8222bfbde8ee6e79703796/
![Homepage widescreen](https://user-images.githubusercontent.com/33105088/77943339-0fd72500-728b-11ea-9ef0-7f3eb87a8ddb.png)

**Comment by kbakeann** [comment]
Exploring charts:
![chart](https://user-images.githubusercontent.com/33105088/77955662-92b5ab00-729e-11ea-907f-1569b2c97e46.png)

**Comment by kbakeann** [comment]
There is already an enhancement issue in place for this: https://github.com/jackneil/covidsc-web/issues/16

**Comment by jackneil** [comment]
We should change the language on the bottom list from 'Confirmed Cases/Deaths By Region' on two small things:
(1) Since we aren't just showing SC, we either need to append the state 2-letter abbreviation after the county or only allow SC counties to be shown. Otherwise it's confusing
(2) Change that title. It isn't really accurate. This is the confirmed case growth rate (it's an exponentially weighted moving average with a multiplier to make the number readable), adjusted for population. Somehow we need that title to reflect this. Maybe 'Case Growth Factor, Population Adjusted, By County' or similar.
Thanks
-jack

**Comment by krumware** [comment]
I'm opting for 1 and 2

**Comment by kbakeann** [comment]
@jackneil I think we should only show SC counties here, as showing other counties might be extraneous and confusing for users. Also don't think a user is going to visit a site named CovidSC and _expect_ to see data from other counties in other states. If we do show that data we'll need to make it more obvious that this is showing data outside of South Carolina and we'll need to be able to filter through those counties.
Thoughts?

**Comment by krumware** [comment]
Its already updated to only show SC counties as of last night, just called it `Confirmed Case Growth Factor By County`
We can add a hint line (like the example above, near the dropdown menu), if we need to explain it further. It also shouldn't get all sciency and freak people out.
